/**
 * Created by chris_000 on 9/26/2015.
 */
export const TRANSACTION_OPERATION_STARTED = 'TRANSACTION_OPERATION_STARTED';
export const TRANSACTION_OPERATION_SUCCESS = 'TRANSACTION_OPERATION_SUCCESS';
export const TRANSACTION_OPERATION_FAILURE = 'TRANSACTION_OPERATION_FAILURE';

export const SET_PAGE = 'SET_PAGE';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CURRENT_MODAL_WAITING = 'CURRENT_MODAL_WAITING';
export const SET_WINDOW_SIZES = 'SET_WINDOW_SIZES';
